# Generated by Django 4.0.5 on 2022-06-29 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0009_alter_payment_expiry_date_alter_payment_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 28, 19, 44, 28, 778708), null=True),
        ),
    ]
